% define properties
dpath = '/raid/sharp/matlab/GOBAI/Data/'; cd(dpath);
cmems.path = '/home/sharp/.conda/envs/copernicusmarine/bin/';
cmems.usr = 'jsharp'; cmems.pwd = 'jvqsEZL9';
y = 2019; m = 12; d = 25; depth = 250;
lat_lims = [0 70]; lon_lims = [-180 -10];

% download glorys for specified data
glorys_data_id = 'cmems_mod_glo_phy_my_0.083deg_P1D-m';
system([cmems.path 'copernicusmarine ' ...
    'subset --skip-existing --dataset-id ' glorys_data_id ...
    ' --start-datetime ' num2str(y) '-' sprintf('%02d',m) '-' ...
    sprintf('%02d',d) ' --end-datetime ' num2str(y) ...
    '-' sprintf('%02d',m) '-' sprintf('%02d',d) ...
    ' --username ' cmems.usr ' --password ' cmems.pwd]);

% download bgc hindcast for specified data
bgc_data_id = 'cmems_mod_glo_bgc_my_0.25deg_P1D-m';
system([cmems.path 'copernicusmarine ' ...
    'subset --skip-existing --dataset-id ' bgc_data_id ...
    ' --start-datetime ' num2str(y) '-' sprintf('%02d',m) '-' ...
    sprintf('%02d',d) ' --end-datetime ' num2str(y) ...
    '-' sprintf('%02d',m) '-' sprintf('%02d',d) ...
    ' --username ' cmems.usr ' --password ' cmems.pwd]);
cd '/raid/sharp/matlab/GOBAI'

% define file names
phys_name = ['cmems_mod_glo_phy_my_0.083deg_P1D-m_multi-vars_180.00W' ...
    '-179.92E_80.00S-90.00N_0.49-5727.92m_' num2str(y) '-' ...
    sprintf('%02d',m) '-' sprintf('%02d',d)];
bgc_name = ['cmems_mod_glo_bgc_my_0.25deg_P1D-m_multi-vars_180.00W' ...
    '-179.75E_80.00S-90.00N_0.51-5902.06m_' num2str(y) '-' ...
    sprintf('%02d',m) '-' sprintf('%02d',d)];

% load physical variables
vars = {'depth' 'latitude' 'longitude' 'time' 'so' 'thetao'};
for v = 1:length(vars)
    glorys.(vars{v}) = single(ncread(['Data/' phys_name '.nc'],vars{v}));
end

% load bgc variables
vars = {'depth' 'latitude' 'longitude' 'time' 'o2'};
for v = 1:length(vars)
    bgc.(vars{v}) = single(ncread(['Data/' bgc_name '.nc'],vars{v}));
end

% calculate ancillary properties
[glorys.lon,glorys.lat,glorys.z] = ...
    ndgrid(glorys.longitude,glorys.latitude,glorys.depth);
[~,depth_idx] = min(abs(glorys.depth-depth));
glorys.pressure = gsw_p_from_z(-glorys.z(:,:,depth_idx),glorys.lat(:,:,depth_idx));
glorys.sal_abs = gsw_SA_from_SP(glorys.so(:,:,depth_idx),glorys.pressure,glorys.lon(:,:,depth_idx),glorys.lat(:,:,depth_idx));
glorys.tmp_cns = gsw_CT_from_pt(glorys.sal_abs,glorys.thetao(:,:,depth_idx));

% apply gobai empirical models to glorys
doy = datenum(y,m,d) - datenum(y,0,0);
oxy = algobai(20,'lat',glorys.lat(:,:,depth_idx),'lon',glorys.lon(:,:,depth_idx),...
    'pres',glorys.pressure,'temp_cns',glorys.tmp_cns,'sal_abs',glorys.sal_abs,'doy',...
    repmat(doy,length(glorys.longitude),length(glorys.latitude)),...
    'year',repmat(y,length(glorys.longitude),length(glorys.latitude)));
oxy = reshape(oxy,length(glorys.longitude),length(glorys.latitude));

% plot glorys empirical o2 (130m)
figure('Position',[100 100 1000 600]);
worldmap(lat_lims,lon_lims);
pcolorm(double(glorys.latitude),double(glorys.longitude),double(oxy)');
title({'Empirical Oxygen from GLORYS (GOBAI alg.)';['(' ...
    datestr(datenum(1950,1,1,double(glorys.time),0,0),'mmm-dd-yyyy') ...
    ', ' num2str(depth) ' m, \mumol kg^{-1})']},'FontSize',16);
shading flat; colorbar; caxis([0 300]);
colormap(cmocean('ice'));
plot_land('map'); mlabel off; plabel off;
export_fig(gcf,['Figures/GLORYS_O2_' sprintf('%02d',m) '-' num2str(y) ...
    '-' num2str(depth) 'm.png'],'-transparent');
close

% plot bgc hindcast o2 (133m)
figure('Position',[100 100 1000 600]);
worldmap(lat_lims,lon_lims);
[~,depth_idx_bgc] = min(abs(bgc.depth-depth));
pcolorm(double(bgc.latitude),double(bgc.longitude),double(bgc.o2(:,:,depth_idx_bgc))');
title({'GLOBAL-MULTIYEAR-BGC Oxygen';['(' ...
    datestr(datenum(1950,1,1,double(bgc.time),0,0),'mmm-dd-yyyy') ...
    ', ' num2str(depth) ' m, \mumol kg^{-1})']},'FontSize',16);
shading flat; colorbar; caxis([0 300]);
colormap(cmocean('ice'));
plot_land('map'); mlabel off; plabel off;
export_fig(gcf,['Figures/MULTIYEAR_BGC_O2_' sprintf('%02d',m) '-' ...
    num2str(y) '-' num2str(depth) 'm.png'],'-transparent');
close

% plot gobai o2 (130m)
ver = 'v1.1-HR';
folder = ['/raid/Data/GOBAI-O2/' ver '/'];
file = ['GOBAI-O2-' ver '.nc'];
gobai.lat = ncread([folder file],'lat');
gobai.lon = ncread([folder file],'lon');
gobai.pres = ncread([folder file],'pres');
gobai.time = ncread([folder file],'time');
[~,pres_idx] = min(abs(gobai.pres-depth));
[~,time_idx] = min(abs((datenum(1950,1,1)+gobai.time)-datenum(y,m,d)));
gobai.o2 = ncread([folder file],'o2',[1 1 pres_idx time_idx],[Inf Inf 1 1]);
figure('Position',[100 100 1000 600]);
worldmap(lat_lims,lon_lims);
pcolorm(gobai.lat,gobai.lon,gobai.o2');
title({'GOBAI-HR-v1.1 Oxygen';['(' datestr(datenum(1950,1,1)+gobai.time(time_idx),'mmm-dd-yyyy') ...
    ', ' num2str(depth) ' m, \mumol kg^{-1})']},'FontSize',16);
shading flat; colorbar; caxis([0 300]);
colormap(cmocean('ice'));
plot_land('map'); mlabel off; plabel off;
export_fig(gcf,['Figures/GOBAI_HR_O2_' sprintf('%02d',m) '-' num2str(y) ...
    '-' num2str(depth) 'm.png'],'-transparent');
close

% plot woa (130m)
file = ['/raid/Data/WOA23/OXYGEN/woa23_all_o' sprintf('%02d',m) '_01.nc'];
woa.lat = ncread(file,'lat');
woa.lon = ncread(file,'lon');
woa.depth = ncread(file,'depth');
[~,depth_idx_woa] = min(abs(woa.depth-depth));
woa.o2 = ncread(file,'o_an',[1 1 depth_idx_woa 1],[Inf Inf 1 1]);
figure('Position',[100 100 1000 600]);
worldmap(lat_lims,lon_lims);
pcolorm(double(woa.lat),double(woa.lon),double(woa.o2)');
title({'WOA23 Oxygen';['(' datestr(datenum(0,8,0),'mmm') ', ' num2str(depth) ...
    ' m, \mumol kg^{-1})']},'FontSize',16);
shading flat; colorbar; caxis([0 300]);
colormap(cmocean('ice'));
plot_land('map'); mlabel off; plabel off;
export_fig(gcf,['Figures/WOA_O2' sprintf('%02d',m) '-' ...
    num2str(depth) 'm.png'],'-transparent');
close

% plot bgc hindcast vs. glorys empirical o2
glorys_oxy_interp_bgc = interp2(permute(glorys.lon(:,:,depth_idx),[2 1]),...
    permute(glorys.lat(:,:,depth_idx),[2 1]),...
    permute(oxy,[2 1]),...
    repmat(bgc.longitude,1,length(bgc.latitude)),...
    repmat(bgc.latitude',length(bgc.longitude),1));
figure('Position',[100 100 1000 600]);
worldmap(lat_lims,lon_lims);
pcolorm(double(bgc.latitude),double(bgc.longitude),...
    (double(bgc.o2(:,:,depth_idx))-glorys_oxy_interp_bgc)');
title({'GLOBAL-MULTIYEAR-BGC Oxygen -';...
    'Empirical Oxygen from GLORYS (GOBAI alg.)';['(' ...
    datestr(datenum(1950,1,1,double(bgc.time),0,0),'mmm-dd-yyyy') ...
    ', ' num2str(depth) ' m, \mumol kg^{-1})']},'FontSize',16);
shading flat; colorbar; caxis([-100 100]);
colormap(cmocean('balance','pivot',0));
plot_land('map'); mlabel off; plabel off;
export_fig(gcf,['Figures/MULTIYEAR_BGC_O2_minus_GLORYS_Empirical_' ...
    sprintf('%02d',m) '-' num2str(y) '-' num2str(depth) 'm.png'],'-transparent');
close

% plot gobai vs. glorys empirical o2
gobai.lon_temp = convert_lon(gobai.lon,'format','-180-180');
[gobai.lon_temp,lon_idx] = sort(gobai.lon_temp);
gobai.o2_temp = gobai.o2(lon_idx,:);
glorys_oxy_interp_gobai = interp2(permute(glorys.lon(:,:,depth_idx),[2 1]),...
    permute(glorys.lat(:,:,depth_idx),[2 1]),...
    permute(oxy,[2 1]),...
    repmat(gobai.lon_temp,1,length(gobai.lat)),...
    repmat(gobai.lat',length(gobai.lon_temp),1));
figure('Position',[100 100 1000 600]);
worldmap(lat_lims,lon_lims);
pcolorm(double(gobai.lat),double(gobai.lon_temp),...
    (double(gobai.o2_temp)-glorys_oxy_interp_gobai)');
title({'GOBAI-HR-v1.1 Oxygen -';...
    'Empirical Oxygen from GLORYS (GOBAI alg.)';['(' ...
    datestr(datenum(1950,1,1)+gobai.time(time_idx),'mmm-dd-yyyy') ...
    ', ' num2str(depth) ' m, \mumol kg^{-1})']},'FontSize',16);
shading flat; colorbar; caxis([-100 100]);
colormap(cmocean('balance','pivot',0));
plot_land('map'); mlabel off; plabel off;
export_fig(gcf,['Figures/GOBAI_O2_minus_GLORYS_Empirical_' ...
    sprintf('%02d',m) '-' num2str(y) '-' num2str(depth) 'm.png'],'-transparent');
close

% plot bgc hindcast vs. woa
oxy_interp_bgc_woa = ...
    interp2(repmat(bgc.longitude',length(bgc.latitude),1),...
    repmat(bgc.latitude,1,length(bgc.longitude)),...
    bgc.o2(:,:,depth_idx_bgc)',...
    repmat(woa.lon,1,length(woa.lat)),...
    repmat(woa.lat',length(woa.lon),1));
figure('Position',[100 100 1000 600]);
worldmap(lat_lims,lon_lims);
pcolorm(double(woa.lat),double(woa.lon),...
    (oxy_interp_bgc_woa - woa.o2)');
title({'GLOBAL-MULTIYEAR-BGC Oxygen -';...
    'WOA23 Oxygen';['(' ...
    datestr(datenum(1950,1,1,double(bgc.time),0,0),'mmm-dd-yyyy') ...
    ', ' num2str(depth) ' m, \mumol kg^{-1})']},'FontSize',16);
shading flat; colorbar; caxis([-100 100]);
colormap(cmocean('balance','pivot',0));
plot_land('map'); mlabel off; plabel off;
export_fig(gcf,['Figures/MULTIYEAR_BGC_O2_minus_WOA_O2_' ...
    sprintf('%02d',m) '-' num2str(y) '-' num2str(depth) 'm.png'],'-transparent');
close

% plot glorys empirical vs. woa
oxy_interp_glorys_woa = ...
    interp2(permute(glorys.lon(:,:,depth_idx),[2 1]),...
    permute(glorys.lat(:,:,depth_idx),[2 1]),...
    permute(oxy,[2 1]),...
    repmat(woa.lon,1,length(woa.lat)),...
    repmat(woa.lat',length(woa.lon),1));
figure('Position',[100 100 1000 600]);
worldmap(lat_lims,lon_lims);
pcolorm(double(woa.lat),double(woa.lon),...
    (oxy_interp_glorys_woa - woa.o2)');
title({'Empirical Oxygen from GLORYS (GOBAI alg.) -';...
    'WOA23 Oxygen';['(' ...
    datestr(datenum(1950,1,1,double(glorys.time),0,0),'mmm-dd-yyyy') ...
    ', ' num2str(depth) ' m, \mumol kg^{-1})']},'FontSize',16);
shading flat; colorbar; caxis([-100 100]);
colormap(cmocean('balance','pivot',0));
plot_land('map'); mlabel off; plabel off;
export_fig(gcf,['Figures/GLORYS_Empirical_O2_minus_WOA_O2_' ...
    sprintf('%02d',m) '-' num2str(y) '-' num2str(depth) 'm.png'],'-transparent');
close

% plot gobai vs. woa
gobai.lon_temp = convert_lon(gobai.lon,'format','-180-180');
[gobai.lon_temp,lon_idx] = sort(gobai.lon_temp);
gobai.o2_temp = gobai.o2(lon_idx,:);
oxy_interp_gobai_woa = ...
    interp2(repmat(gobai.lon_temp',length(gobai.lat),1),...
    repmat(gobai.lat,1,length(gobai.lon_temp)),gobai.o2_temp',...
    repmat(woa.lon,1,length(woa.lat)),...
    repmat(woa.lat',length(woa.lon),1));
figure('Position',[100 100 1000 600]);
worldmap(lat_lims,lon_lims);
pcolorm(double(woa.lat),double(woa.lon),...
    (oxy_interp_gobai_woa - woa.o2)');
title({'GOBAI-HR-v1.1 Oxygen -';...
    'WOA23 Oxygen';['(' ...
    datestr(datenum(1950,1,1)+gobai.time(time_idx),'mmm-dd-yyyy') ...
    ', ' num2str(depth) ' m, \mumol kg^{-1})']},'FontSize',16);
shading flat; colorbar; caxis([-100 100]);
colormap(cmocean('balance','pivot',0));
plot_land('map'); mlabel off; plabel off;
export_fig(gcf,['Figures/GOBAI_O2_versus_WOA_O2_' ...
    sprintf('%02d',m) '-' num2str(y) '-' num2str(depth) 'm.png'],'-transparent');
close
