% define_variables_for_model
function variables = define_variables_for_model(); 
variables = ...
    {'latitude' 'longitude' 'sigma' 'pressure' 'temperature_cns' ...
    'salinity_abs' 'lon_cos' 'year' 'day_sin' 'day_cos'};