% o2 transect
plot_gobai_transect_animation(param_props,'/raid/Data/GOBAI-O2/v1.0-HR',...
    base_grid,num_clusters,'FFNN',...
    file_date,float_file_ext,numWorkers_predict,'train_ratio',train_ratio,...
    'val_ratio',val_ratio,'test_ratio',test_ratio);

plot_gobai_zonal_animation(param_props,'/raid/Data/GOBAI-O2/v1.0-HR',...
    base_grid,num_clusters,'FFNN',...
    file_date,float_file_ext,numWorkers_predict,'train_ratio',train_ratio,...
    'val_ratio',val_ratio,'test_ratio',test_ratio);

% dic
plot_gobai_animation(param_props,'/raid/Data/GOBAI-DIC/v1.0-HR',...
    base_grid,num_clusters,'FFNN',...
    file_date,float_file_ext,numWorkers_predict,'train_ratio',train_ratio,...
    'val_ratio',val_ratio,'test_ratio',test_ratio);

% dic transect
plot_gobai_transect_animation(param_props,'/raid/Data/GOBAI-DIC/v1.0-HR',...
    base_grid,num_clusters,'FFNN',...
    file_date,float_file_ext,numWorkers_predict,'train_ratio',train_ratio,...
    'val_ratio',val_ratio,'test_ratio',test_ratio);

% no3
param_props.edges = 0:0.5:40;
plot_gobai_animation(param_props,'/raid/Data/GOBAI-NO3/v1.0-HR',...
    base_grid,num_clusters,'FFNN',...
    file_date,float_file_ext,numWorkers_predict,'train_ratio',train_ratio,...
    'val_ratio',val_ratio,'test_ratio',test_ratio);