% run_osse
%
% DESCRIPTION:
% This function use the combined dataset to subsample models,
% train test machine learning algorithms, and apply those
% algorithms to model grids to test their performance.
%
% AUTHOR: J. Sharp, UW CICOES / NOAA PMEL
%
% DATE: 11/1/2024

function run_osse(model_path,param_props,file_date,snap_date,float_file_ext,...
    num_clusters,variables,clust_vars,train_ratio,val_ratio,test_ratio,...
    numtrees,minLeafSize,numstumps,numbins,thresh,numWorkers_train,numWorkers_predict)

%% load combined data
load([param_props.dir_name '/Data/processed_all_' param_props.file_name '_data_' file_date float_file_ext '.mat'],...
     'all_data','file_date');

%% define models
model_types = {'GFDL-ESM4' 'CanESM5' 'IPSL-CM6A-LR' 'ACCESS-ESM1-5' 'MPI-ESM1-2-LR'};
model_folders = {'GFDL-ESM4' 'CanESM5' 'IPSL-CM6A-LR' 'ACCESS-ESM1-5' 'MPI-ESM1-2-LR'};
realizations = {'r1i1dir_namef1' 'r1i1dir_namef1' 'r1i1dir_namef1' 'r1i1dir_namef1' 'r1i1dir_namef1'};
grid_labels = {'gr' 'gn' 'gn' 'gn' 'gn'};
grid_types = {'regridded' 'native_grid' 'native_grid' 'native_grid' 'native_grid'};

%% loop through each model
for m = 1:length(model_types)

    %% process models
    process_cmip_model(model_types{m},[model_path model_folders{m} '/'],...
        snap_date,2004,realizations{m},grid_labels{m},grid_types{m});

    %% subsample models
    subsample_cmip_model(param_props,all_data,model_types{m},...
        [model_path model_folders{m} '/'],file_date,...
        snap_date,float_file_ext,2004,realizations{m});
  
    %% form clusters
    gmm_clustering(param_props,[model_path model_folders{m} '/'],model_types{m},...
        2004,snap_date,float_file_ext,clust_vars,num_clusters,...
        numWorkers_predict,[model_path model_folders{m} '/']);
    % plot_cluster_animation([model_path model_folders{m} '/'],model_types{m},num_clusters,2004,snap_date);
    
    %% cluster data
    assign_data_to_clusters(param,model_types{m},file_date,snap_date,float_file_ext,clust_vars,num_clusters);
    plot_data_by_cluster(param,model_types{m},file_date,float_file_ext,num_clusters,numWorkers_train);
    % plot_data_over_clusters(param,model_types{m},file_date,float_file_ext,num_clusters,numWorkers_train);

    %% train algorithms
    data_per = 0.05; % fraction for reducing training data volume
    % train feed forward neural networks
    train_gobai('FFNN',param,model_types{m},file_date,float_file_ext,...
        num_clusters,variables,thresh,numWorkers_train,snap_date,'reduce_data',...
        data_per,'train_ratio',train_ratio,'val_ratio',val_ratio,...
        'test_ratio',test_ratio);
    % train random forest regressions
    train_gobai('RFR',param,model_types{m},file_date,float_file_ext,...
        num_clusters,variables,thresh,numWorkers_train,snap_date,'reduce_data',...
        data_per,'numtrees',numtrees,'minLeafSize',minLeafSize);
    % train gradient-boosting machines
    train_gobai('GBM',param,model_types{m},file_date,float_file_ext,...
        num_clusters,variables,thresh,numWorkers_train,snap_date,'reduce_data',...
        data_per,'numstumps',numstumps,'numbins',numbins);

    %% predict on grid
    % predict on grid using feed forward neural networks
    predict_gobai('FFNN',param,[model_path model_folders{m} '/'],...
        model_types{m},file_date,float_file_ext,num_clusters,variables,thresh,...
        numWorkers_predict,2004,snap_date,'train_ratio',train_ratio,...
        'val_ratio',val_ratio,'test_ratio',test_ratio,...
        'rlz',realizations{m});
    % predict on grid using random forest regressions
    predict_gobai('RFR',param,[model_path model_folders{m} '/'],...
        model_types{m},file_date,float_file_ext,num_clusters,...
        variables,thresh,numWorkers_predict,2004,snap_date,...
        'numtrees',numtrees,'minLeafSize',minLeafSize,...
        'rlz',realizations{m});
    % predict on grid using gradient-boosting machines
    predict_gobai('GBM',param,[model_path model_folders{m} '/'],...
        model_types{m},file_date,float_file_ext,num_clusters,...
        variables,thresh,numWorkers_predict,2004,snap_date,...
        'numstumps',numstumps,'numbins',numbins,...
        'rlz',realizations{m});

    %% average grids across all algorithms
    combine_gobai(param,[model_path model_folders{m} '/'],...
        model_types{m},file_date,float_file_ext,...
        num_clusters,2004,snap_date,train_ratio,...
        val_ratio,test_ratio,numtrees,minLeafSize,...
        numstumps,numbins,'rlz',realizations{m});

    %% compare reconstructed model grid to original
    compare_osse(param,param1,[model_path model_folders{m} '/'],...
        model_types{m},file_date,float_file_ext,...
        num_clusters,2004,snap_date,train_ratio,...
        val_ratio,test_ratio,numtrees,minLeafSize,...
        numstumps,numbins,realizations{m});

end

compare_all_osses(param,param1,model_types,realizations,num_clusters,file_date,float_file_ext);
