%% Run all scripts to make GOBAI-pH
create_config_files; % creates configuration files used by GOBAI code
load_standard_config_files; % loads the 'standard' set of configuration files
load('Config/sockeye.mat'); % change 'workers' configuration to chinook
load('Config/base_config_RG.mat'); % change 'base_grid' to Roemmich and Gilson
data_per = 0.1; % set data reduction to 10%
param = 'ph'; param_props = param_config(param);

%% load and process data
% acquire data
acquire_snapshot_data(param_props,data_modes,float_file_ext,snap_date,snap_download);
acquire_glodap_data(param_props,glodap_year);
% display data
display_data(param_props,float_file_ext,glodap_year);
% adjust and combine data
adjust_ph_float_data(float_file_ext,glodap_year);
combine_data(param_props,float_file_ext,glodap_year);

%% create time-varying clusters and assign data points to them
% form clusters
gmm_clustering(param_props,pwd,base_grid,2004,snap_date,...
    float_file_ext,clust_vars,num_clusters,numWorkers_predict);
% plot cluster animations
plot_cluster_animation(param_props,pwd,base_grid,num_clusters,2004,...
    snap_date,numWorkers_train);
%plot_probability_animation(base_grid,num_clusters);
% cluster data
assign_data_to_clusters(param_props,base_grid,snap_date,float_file_ext,clust_vars,num_clusters);
% plot clustered data points
plot_data_by_cluster(param_props,base_grid,file_date,float_file_ext,num_clusters,numWorkers_train);
%plot_data_over_clusters(param,base_grid,file_date,float_file_ext,num_clusters,numWorkers_train);
% develop k-fold evaluation indices
kfold_split_data(param_props,base_grid,file_date,float_file_ext,glodap_only,num_clusters,num_folds,thresh);

%% k-fold train models for evaluation statistics
% feed-forward neural networks
train_gobai('FFNN',param_props,base_grid,file_date,float_file_ext,...
    num_clusters,variables,thresh,numWorkers_train,snap_date,'reduce_data',...
    data_per,'train_ratio',train_ratio,'val_ratio',val_ratio,...
    'test_ratio',test_ratio,'num_folds',num_folds);
% random forest regressions
train_gobai('RFR',param_props,base_grid,file_date,float_file_ext,...
    num_clusters,variables,thresh,numWorkers_train,snap_date,'reduce_data',...
    data_per,'numtrees',numtrees,'minLeafSize',minLeafSize,...
    'num_folds',num_folds);
% gradient-boosting machines
train_gobai('GBM',param_props,base_grid,file_date,float_file_ext,...
    num_clusters,variables,thresh,numWorkers_train,snap_date,'reduce_data',...
    data_per,'numstumps',numstumps,'numbins',numbins,...
    'num_folds',num_folds);

%% train models to create GOBAI product
% feed-forward neural networks
train_gobai('FFNN',param_props,base_grid,file_date,float_file_ext,...
    num_clusters,variables,thresh,numWorkers_train,snap_date,'reduce_data',...
    data_per,'train_ratio',train_ratio,'val_ratio',val_ratio,...
    'test_ratio',test_ratio);
% random forest regressions
train_gobai('RFR',param_props,base_grid,file_date,float_file_ext,...
    num_clusters,variables,thresh,numWorkers_train,snap_date,'reduce_data',...
    data_per,'numtrees',numtrees,'minLeafSize',minLeafSize);
% gradient-boosting machines
train_gobai('GBM',param_props,base_grid,file_date,float_file_ext,...
    num_clusters,variables,thresh,numWorkers_train,snap_date,'reduce_data',...
    data_per,'numstumps',numstumps,'numbins',numbins);

%% estimate parameter on grid to create GOBAI product
% feed-forward neural networks
% predict_gobai('FFNN',param_props,pwd,base_grid,file_date,float_file_ext,...
%     num_clusters,variables,thresh,numWorkers_predict,2004,...
%     snap_date,'train_ratio',train_ratio,'val_ratio',val_ratio,...
%     'test_ratio',test_ratio);
% plot_gobai_animation(param_props,base_grid,num_clusters,'FFNN',...
%     file_date,float_file_ext,numWorkers_predict,'train_ratio',train_ratio,...
%     'val_ratio',val_ratio,'test_ratio',test_ratio);
% % random forest regressions
% predict_gobai('RFR',param_props,pwd,base_grid,file_date,float_file_ext,...
%     num_clusters,variables,thresh,numWorkers_predict,2004,...
%     snap_date,'numtrees',numtrees,'minLeafSize',minLeafSize);
plot_gobai_animation(param_props,base_grid,num_clusters,'RFR',...
    file_date,float_file_ext,numWorkers_predict,'numtrees',numtrees,'minLeafSize',minLeafSize);
% gradient-boosting machines
predict_gobai('GBM',param_props,pwd,base_grid,file_date,float_file_ext,...
    num_clusters,variables,thresh,numWorkers_predict,2004,...
    snap_date,'numstumps',numstumps,'numbins',numbins);
plot_gobai_animation(param_props,base_grid,num_clusters,'RFR',...
    file_date,float_file_ext,numWorkers_predict,'numstumps',numstumps,'numbins',numbins);

%% assemble ensemble mean GOBAI
% combine_gobai(param,pwd,base_grid,file_date,float_file_ext,...
%         num_clusters,2004,snap_date,train_ratio,...
%         val_ratio,test_ratio,numtrees,minLeafSize,...
%         numstumps,numbins);
% plot_gobai_animation(param_props,base_grid,num_clusters,'ENS',...
%     file_date,float_file_ext);

%% run OSSEs
% run_osse(param,file_date,snap_date,float_file_ext,num_clusters,...
%     variables,clust_vars,train_ratio,val_ratio,test_ratio,numtrees,...
%     minLeafSize,numstumps,numbins,thresh,numWorkers_train,numWorkers_predict);

%% determine uncertainty
% calculate_gridding_uncertainty;
